shinetext/torch

config/hugo.config.toml
config/webpack.config.js
hugo/layouts/_default/article_card_preview.html
hugo/layouts/_default/featured_article.html
hugo/layouts/_default/single.html
hugo/layouts/index.html
hugo/layouts/partials/article_author_section.html
hugo/lib/createArticle.js
hugo/lib/getArticles.js
package.json

Added scripts to create hugo content from contentful after every rebuild
Fixed markdown bug involving warping <p> tags.
Look through the hugo/lib directory the major changes are there.
I anticipate most of the single.html and index.html will change a lot after we get Kim's new designs so I wouldn't spend too much time there.
issue: #1 
The markdown fix works but if you know of a better solution to wrapping <p> tags. I tried two solutions. extracting all p tags from markdown before passing it to Hugo or using the "marked" library to pre-render it before it gets to Hugo. The first solution looks funky.

Add scripts to format and create article markdown from contentful 

---

hugo/layouts/partials/extra/meta_og.html
hugo/layouts/partials/extra/meta_twitter.html
hugo/layouts/partials/head.html
hugo/lib/createArticle.js
src/js/components/Header.js

- Updates the `createArticle` step to include the content description in the article template.
- Adds an `og` and `twitter` section to the `head` of the page that gets populated by the content's param values.
- ~Removes an extra plus-icon in the mobile menu. This isn't meant to be there is it?~
- UPDATE: jk, adding that icon back in. Just updating the mobile menu categories to reflect the 4 we're launching with.
Fetched content for staging and ran a local server. Verified the tags were there and populated with the article's content.
After deploy we'll want to test the staging links at least again the Twitter and Facebook card validators.
- https://cards-dev.twitter.com/validator
- https://developers.facebook.com/tools/debug/

Adds og and twitter meta tags for social sharing

---

hugo/lib/createArticle.js

Fixes scenarios where the slug is different than what the article title would've normally generated.
A couple cases where this was seen happening was for:
- /articles/how-this-shine-squad-member-stopped-comparing-himself-to-others
- /articles/shine-squad-feature-ninas-4-tips-to-slow-down-and-enjoy-life/
Without this change the articles instead would've been:
- /articles/shine-squad-feature-how-i-stopped-comparing-myself/
- /articles/4-tips-to-slow-down-and-enjoy-life/
It looked like without the slug, Hugo would generate the URL path based on the `title` as opposed to the filename. Does it make sense that that's what happening?
Tested the above 2 articles and their URL paths, plus several others on a local environment.

Adds slug to the generated article content

---

hugo/layouts/_default/single.html
hugo/lib/createArticle.js

Fixes a bug involving Hugo's markdown parser and p tags. Removed markdown parsing from Hugo single template. 
Locally after fetching all the blog articles and removing the ``` {{ .Content | Markdownify }} ``` maked wraps the content in a p tag.
Bug found when testing staging for production
Painful but nessecary.

first paragraph fix

---

hugo/lib/createArticle.js

Fixes a previous change that caused extra content at the bottom of the article from getting cut off.
We'd get the index of the pubx module, if any here:
```
let idxOfPubExMod = body.indexOf('<div class="pubexchange_module"');
```
But then we'd render the `body` from markdown first and then remove content second here:
```
marked(body).slice(0, idxOfPubExMod);
```
We still need to slice off the pubx code first before parsing the markdown.
Verified content in Contentful matches up with what ends up getting rendered.
We should probably consider removing the Pub Exchange code from the content body of all the articles and just leaving it to the template to take care of it. Removing it will simplify the logic we've got going on in createArticle.js.
cc: @kaladin9017

Fixes content at bottom of the article getting cut off

---

src/less/blog-v2/includes/latest-articles.less

Fix bug with safari and setting height of flexbox child to 100%. Removed height and changed it to use flex grow instead. 
Using safari 10. 
I didn't use an autoprefixer for the less/css something to think about for any other browser compatibility.

fix safari browser bug

---

.gitignore
hugo/lib/createPromotedJson.js
hugo/lib/getArticles.js

Create a json feed with 6 articles for http://advice.shinetext.com/promoted.json
Tested on my local to ensure each article had fields used in the ejs template to render the html feed
#13
I used an additional try catch instead of the same block. Not 100% sure but I didn't want an error in building the promoted feed to impact the rebuild on the main blog.

add script to create promoted json feed

---

hugo/static/_headers

Adds _headers file to enable CORS on the promoted.json file. The promoted.json file is fetched by the Shine homepage on a different subdomain.
Was testing with a local version of aurora. Ensured that the setup on localhost could fetch the promoted.json file on the deploy preview version created by this PR.
#67 
After this we can then make the update in [aurora](github.com/shinetext/aurora) to use the promoted.json here again.
cc: @cl2205

Adds _headers file to enable CORS on the promoted.json file

---

hugo/layouts/partials/footer.html
hugo/static/scripts/slideup.js
src/less/blog-v2/includes/article-card.less

Adds parallax to homepage.   
Tested using chrome dev tools.
#8 
The animation doesn't work properly on cards listed on the articles/author/category pages. The infinite loader appends the cards to the container immediately and the scroll event handler ignores them. I tried a few different fixes but because the cards append into the view the animation slides down then up.

add slide up/parallax to homepage

---

hugo/lib/getArticles.js

Update the promoted Json file to only include articles that have been published to staging.
Tested locally by running build scripts and then inspecting ``` promoted.json ``` file.
No issue just a bug
N/A

update build script to only update production articles to promoted json

---

hugo/layouts/_default/single.html
src/less/blog-v2/variables/sizes.less

Like the title says, just increases the height of that article image. This only applies to desktop view widths.
Increasing the height helps the majority of the images we're choosing for the articles work in both the homepage/card views and in the bigger view at the top of the article page. And in turn helps save our time on the content side when trying to find photos that'll work in the different views.
Just did some local testing. Screenshots below to highlight the difference
**412px:**
**540px:**
Are there any other elements on the article page that could be influenced by this change like the signup popup?

Increases max height of the article image to 540px from 412px

---

config/hugo.config.base.toml
hugo/layouts/partials/head.html
hugo/lib/createArticle.js

Appends " | Shine" to all `title` tags. Removes it from the base site config, otherwise the homepage's title would be "Get Advice | Shine | Shine".
Also trimming whitespace from titles in the build script. Some scenarios were found while testing that resulted in `title` tags that looked like "Article Name    | Shine".
Closes #92

Updates to append ' | Shine' to all titles

---

hugo/layouts/partials/article_modules/article_meta.html

Adds link tags for author meta data. 
Tested using google chrome dev tools. 
N/A
An update for author meta information for article pages. After looking around at other blogs, and asking a few questions on reach flux it seems google ignores author meta data if not paired with a link to the author.

add link to author for SEO

---

hugo/layouts/partials/includes.html
hugo/lib/getArticles.js

Fixes bug where the canonical link wasn't getting set.
This article is the one that should have it: /articles/3-ways-to-make-better-decisions-with-the-power-of-noticing/
We can check the deploy preview to make sure it's got it.
Closes #93

Fixes canonical link typo + getArticles comment update

---

hugo/layouts/partials/extra/meta_og.html

Update meta link for og:url. 
Not sure if this just affects Facebook scraper but the fix will format this URL correctly. 
Tested on my local machine using chrome dev tools.
N/A
n/a

fix og:url meta tag format

---

hugo/lib/getArticles.js

Fix promoted article build step to exclude staging articles.
Tested by running ``` npm run build-for-staging ```
#110
It works. But I could be wrong because I thought it was working before.

exclude staging articles from promoted json

---

hugo/lib/build-content-url.sh
hugo/lib/getUrl.js
hugo/lib/writeRobotsTxt.js

The previous logic wrote the robots.txt file when this was true: `(baseURL !== "https://advice.shinetext.com/")`. But this always evaluated to true because baseURL essentially gets set to a string meant for the hugo.config.base.toml file. `"baseUrl = ${process.env.BASE_URL || "/"}"`
Local testing running npm run build-script-staging and npm run build-script-production and verified the robots.txt file was not written for production builds.

Fixes robots.txt from getting written in production deploys

---

hugo/lib/createArticle.js

Previously, if a `canonical` value was not set, it would set the canonical link to `"undefined"`. Now as an empty string, the logic in **layouts/partials/includes.html** should just place the current URL in there.
Fixes #114 
View source: https://deploy-preview-115--shine-advice-production.netlify.com/articles/the-surprising-power-of-your-life-story/
```
<link rel="canonical" href="https://advice.shinetext.com/articles/the-surprising-power-of-your-life-story/" />
```

Fix to "undefined" canonical links

---

hugo/content/page/about.md
hugo/lib/build-content-url.sh
hugo/lib/writeRobotsTxt.js

- Removing any existing robots.txt file from the static folder during build and deploy
- Writing a new robots.txt file for production that allows robots all access
- And unrelated, just removing the about page since it's not being used, but is still a page that gets built and deployed

Another attempt at fixing the robots.txt on production

---

hugo/static/_redirects

1. Redirects links to removed articles to a similar article.
2. Adds static `_redirect` file to public folder used by netlify. 
Tested using the netlify staging link.
`https://trello.com/c/GSSY0pxC/34-create-redirect-for-a-deleted-page`

Add netlify redirects file to build folder

---

hugo/static/_redirects

Prevent the overextending of the black background of the category span on the blog homepage.

Fix homepage category span. 

---

hugo/layouts/partials/footer.html
hugo/static/scripts/typeform.js

Gives content creators the ability to add typeform polls into articles. 
Before embedding a typeform poll editors must first remove script tag.
Origial won't work
```
<div class="typeform-widget" data-url="https://shine32.typeform.com/to/IK4kxM" style="width: 100%; height: 500px;"></div> 
<script> (function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm", b="https://embed.typeform.com/"; if(!gi.call(d,id)) { js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })() </script> 
<div style="font-family: Sans-Serif;font-size: 12px;color: #999;opacity: 0.5; padding-top: 5px;"> powered by <a href="https://admin.typeform.com/signup?utm_campaign=IK4kxM&utm_source=typeform. …
```

Add typeform script to footer

---

hugo/layouts/_default/baseof.html
hugo/layouts/partials/extra/sumo.html
hugo/layouts/partials/homepage_modules/homepage_meta.html
hugo/layouts/partials/includes.html

- Update meta tag on homepage from 'http' to 'https'
- Replace old sumo install script tag with new version
- Move script tag from header to body of html(Recommended by sumo engineer)
Review using chrome inspector and sharing an article using sumo share bar. 
Bug raised in slack. Article share counts not updating after sharing on twitter.
Example:  `https://advice.shinetext.com/articles/how-to-deal-when-you-just-dont-feel-like-enough/`

Replace old sumo script tag. Move script tag to body of html.

---

src/less/blog-v2/includes/latest-articles.less

Fix category span on featured articles containers on `advice.shinetext.com`
`npm run build-for-staging` && `npm run hugo-server`
https://trello.com/c/XqFeretp/115-fix-category-span-on-featured-articles-containers-on-adviceshinetextcom

Change width of category span on featured article previews.

---

config/hugo.config.base.toml
hugo/layouts/partials/extra/gtm_optimize_container.html
hugo/layouts/partials/extra/gtm_optimize_ph.html
hugo/layouts/partials/includes.html

Adds Google Optimize plugin + related page-hiding script to html header (as separate html partials) for running A/B test experiments.
Ran test Optimize experiments with dev/test GA/optimize spaces/IDs. 
https://trello.com/b/9sBG7hpu/current-sprint-092518-100918

Add google optimize to blog

---

hugo/lib/getArticles.js

We just started running into an error at ~633 articles with the Contentful API: "Response size too big, was: 7354796b. Maximum allowed response size: 7340032b." So by decreasing the number of articles we receive per query, we should be able to safely avoid this error.
Tested locally pulling down content for production. Confirmed that the article that we're currently unable to pull and publish got pulled down to my local setup.
https://shinetext.atlassian.net/browse/SHI-839

Decreases the query limit for article pulls to 250

---

hugo/layouts/partials/footer.html
hugo/lib/createArticle.js
src/js/components/Header.js

- Cleaned up some links in Header & Footer to keep the language around Shine Premium clearer to users
- HACK: add string manipulation to createArticle.js in order to remove line break created by `marked` library that causes issues when Hugo is upgraded to v0.40^
- tested locally
- https://shinetext.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=SHI&modal=detail&selectedIssue=SHI-1008&sprint=18&quickFilter=1

Update links in Nav & Footer

---

config/hugo.config.base.toml
hugo/layouts/rss.xml

This is based off the default template: https://gohugo.io/templates/rss/#the-embedded-rss-xml
I primarily wanted to add a couple fields as needed for Flipboard: https://about.flipboard.com/rss-spec/
So the only two new ones here are really:
- `dc:creator`
- `enclosure`
Just a note too that apparently the file needs to be named **rss.xml**. I tried a couple of the other combinations, but my changes never showed up in the generated feed if I did.
Tested locally with the RSS feed generated locally.
I'll want to double check with the deploy previews to make sure those show the new fields as well.
https://shinetext.atlassian.net/browse/SHI-1199

Adds custom RSS template

---

hugo/layouts/rss.xml
hugo/lib/createArticle.js

Fixes the `enclosure` field in our RSS feed. I was totally wrong about how that field was [suppose to work](https://www.w3schools.com/xml/rss_tag_enclosure.asp).
Since it also needs the media type and size in bytes, we're getting that additional info from the Contentful API and passing it along.
Also removing the xml version 1.0 line because it was getting duplicated. There must a process somewhere else that's adding that line to the top of the file too.
Locally tested. And deploy preview looks good too: https://deploy-preview-167--shine-advice-staging.netlify.com/index.xml
https://shinetext.atlassian.net/browse/SHI-1199

Fixes enclosure RSS field

---

src/less/blog-v2/print.less
src/less/importer.less

Fixes the page styles to be _a lot_ more printer friendly.
The `@media print` query only gets applied to the page when it's getting made to print.
So I just learned this, you can emulate what the printer will see/print in Chrome.
**DevTools > open the menu icon > More tools > Rendering > Emulate CSS media > print**
Before:
After:
https://shinetext.atlassian.net/browse/SHI-1824

Adds a stylesheet for printing

---

hugo/layouts/partials/extra/meta_og.html
hugo/layouts/partials/extra/meta_twitter.html
hugo/layouts/partials/head.html
hugo/lib/createArticle.js

If a `metaTitle` is provided, we'll use that as the copy for:
- `<title>`
- `og:title` meta tag
- `twitter:title` meta tag
This won't affect the article title that's rendered in the `h1` tag.
I've already added `metaTitle` as an optional field in the Article content model on Contentful.
Tested an article with `metaTitle` set and confirmed meta tags were different and article title remained the same. And tested page where no `metaTitle` was set and confirmed all tags and article title remained unchanged.

Adds support for different SEO and article titles

---

hugo/layouts/partials/footer.html
src/js/components/Header.js
src/less/blog-v2/includes/navbar.less

Links to virusanxiety.com added to the header and footer.
Worth noting that in the header menu, I'm replacing what used to be the Self-Care Style Quiz. @angelahum that's ok, right? It's still available in the footer should we need it, but it seemed like we had deprioritized using that.
This shouldn't be pushed to `releases` until the virusanxiety.com site is published.
Local testing. Should be able to use the deploy previews to check it out too.

Adds virusanxiety links to footer and header

---

hugo/layouts/partials/footer.html
src/js/components/Header.js

Updates content and behavior of the top nav and the footer. I don't think it's worth the effort right now to try to style the two sections to match glow-web. But we can at least get the content to more closely match.
Here's what the top nav will now look like.
- On desktop:
- On mobile:
Homepage on my localhost and trying out all the updated links.
https://shinetext.atlassian.net/browse/SHI-2157

Updates to nav and footer

---

hugo/layouts/partials/article_modules/article_post_article.html
hugo/layouts/partials/extra/join_bar.html
hugo/layouts/partials/extra/join_bar_article.html
hugo/layouts/partials/head.html
hugo/layouts/partials/homepage_modules/shine_squad_cards.html
hugo/layouts/robots.txt
src/js/components/Header.js
src/less/blog-v2/main.less

- The robots.txt file fix will the coverage issues detected for the advice.shinetext domain as well as those that'll come up for advice.theshineapp.com.
- Everything else is just for consistency and clarity. The old shinetext redirects will work, but if people hover over the link or copy and share it, we'll want to make sure we're using theshineapp.com.
At least when updating the code, I verified every link I changed still works.

Update hardcoded shinetext links to theshineapp.com

---

src/less/blog-v2/main.less

Since we removed the library background image from glow-web, replacing the missing background image with a solid color background to save on load time.
Places to check: bottom of advice.shinetext.com , bottom of an advice article page

Update cta bg image with bg color

---

hugo/layouts/_default/list.html
src/js/components/Header.js

Adds Work category to the mobile nav
Fixes Care heading on listing page (/categories/care/)
I wasn't able to test on my local because I couldn't run `run hugo-server`, going to check the deploy preview instead.

Add Work category to mobile nav

---

config/hugo.config.base.toml

Migrated the advice tags to the same container as theshineapp.com in order to track with Hubspot.

Update GTM container ID

---

hugo/layouts/_default/baseof.html
hugo/layouts/partials/extra/sumo.html

Saw a message at the bottom of the blog that said Sumo was firing twice. This is because since we moved to the shared GTM container, Sumo is also firing from there so I'm removing the snippet from the codebase.
Will check on staging link

Remove duplicate Sumo tag

---

hugo/lib/getUrl.js

Passes an additional err callback to new `getUrl.js` lines that came from merge conflict with `releases.` Will need this additional cb in order for build to pass in build image update.
And more prettier formatting. Not sure why this didn't come up the 1st time around.
Will check deploy preview and build status.
https://www.notion.so/shinetext/Sept-19-deadline-Netlify-build-image-migration-29e199347ad24469b6f1cdbeed0bb07d

Passes additional err callback to getUrl lines that came from merge conflict with releases
