- config/hugo.config.toml
- hugo/layouts/index.html
- hugo/layouts/partials/article_modules/article_author_section.html
- hugo/layouts/partials/article_modules/article_card_preview.html
- hugo/layouts/partials/article_modules/article_pre_article.html
- hugo/layouts/partials/extra/google_tag_manager.html
- hugo/layouts/partials/extra/read_more.html
- hugo/layouts/partials/homepage_modules/featured_article.html
- hugo/layouts/partials/homepage_modules/homepage_meta.html
- hugo/layouts/partials/includes.html
- hugo/layouts/partials/latest_header.html
- hugo/layouts/partials/social/author_social.html
- hugo/layouts/partials/social/social_modal.html
- src/less/blog-v2/articles.less
- src/less/blog-v2/includes/article-card.less
- src/less/blog-v2/includes/latest-articles.less
- src/less/blog-v2/main.less
- src/less/blog-v2/variables/colors.less
- src/less/blog-v2/variables/fonts.less
- src/less/blog-v2/variables/sizes.less
Style updates to article cards and featured components
> Chris development

- config/hugo.config.base.toml
- hugo/layouts/_default/baseof.html
- hugo/layouts/partials/extra/fb_pixel.html
- hugo/layouts/partials/extra/gtm_body.html
- hugo/layouts/partials/extra/gtm_head.html
- hugo/layouts/partials/includes.html
Adds the Google Tag Manager ID. But also opening up this PR to ask the Qs below.
- I saw that we do already have **extra/google_tag_manager.html**. I'm not sure what the reasoning is behind this line though `{{if eq (getenv "NETLIFY_STAGING") true }}`. If anything, should it be a `NETLIFY_PRODUCTION` env var?
- When I look at the GTM instructions about how to install the script (https://developers.google.com/tag-manager/quickstart) I see that it needs something in the `<head>` tag and another in the `<body>` tag. But in this project it's currently combined in the partial. Any reason we're doing it that way vs. what's in the docs?
Closes #18
> Adds GTM ID

- hugo/layouts/_default/single.html
- hugo/layouts/partials/extra/latest_header.html
- hugo/layouts/partials/extra/popular_header.html
- hugo/layouts/partials/homepage_modules/shine_squad_header.html
- src/less/blog-v2/articles.less
- src/less/blog-v2/main.less
- src/less/blog-v2/variables/colors.less
- src/less/blog-v2/variables/fonts.less
- Miscellaneous updates on the article page that adjust mostly spacing and font sizes.
- Removes the set height on an article's header photo when the screen size drops to a mobile-phone size.
- Site-wide updates to the button color gradient and gradient line height.
- Desktop across various widths
- Mobile phone through ngrok
> Article page spacing and font updates + more

- hugo/layouts/partials/article_modules/pubexchange_module.html
Updates the code for our Pub Exchange integration. Code was provided by their team. Their devs were going to update the styling of the cards in our pubx module once we get it in.
> Updates the Pub Exchange code

- hugo/layouts/partials/article_modules/article_post_article.html
- hugo/layouts/partials/article_modules/article_pre_article.html
- hugo/layouts/partials/extra/join_bar.html
- hugo/layouts/partials/social/author_social.html
- src/less/blog-v2/articles.less
- src/less/blog-v2/main.less
- src/less/blog-v2/variables/colors.less
- src/less/blog-v2/variables/fonts.less
Minor edits to article page template, using input from Kim and  Marah.
The inner article links color and underline doesn't look or feel right as a darker color to me with the underline maybe I'm interpreting Kim's changes wrong?
I used https://www.materialui.co/socialcolors for font colors.
> Article page update

- hugo/layouts/partials/homepage_modules/latest_articles.html
- hugo/layouts/partials/homepage_modules/latest_articles_second_section.html
- src/less/blog-v2/includes/article-card.less
- src/less/blog-v2/includes/latest-articles.less
- src/less/blog-v2/includes/popular-articles.less
- src/less/blog-v2/main.less
- src/less/blog-v2/variables/fonts.less
Aligns the popular feature components. Decreased font size of article cards by 4px. 
Change layout of main page so popular articles don't appear twice. 
Ngrok and chrome dev tools.
I reduced the font size of the article card preview down 4px and it did look better on the popular article section but for every other view it feels too small.  Can you try it on your local and see what you think?
> style changes to homepage and layout changes to latest article section

- hugo/layouts/partials/extra/join_bar.html
Add utm tag to joinbar template. 
#36 
Is it possible to change the name of the utm tag from footer-button to blog/join-bar?
> add utm tag to footer

- hugo/layouts/partials/homepage_modules/shine_squad_cards.html
- src/less/blog-v2/includes/shine-squad-cards.less
Adds the static information about shine squad members to the homepage template
Ngrok and chrome dev tools
Not sure if the links will work properly pointing to http when we switch over to netlify.
> add static shine-squad info to template

- hugo/layouts/partials/article_modules/article_post_article.html
- hugo/layouts/partials/article_modules/article_pre_article.html
- src/js/components/SmsShare.js
- src/js/main.js
- src/less/blog-v2/articles.less
Adds sms share to article page template on mobile views. 
I used chrome devtools for the different views and tested on both my galaxy and iphone. 
First time creating a SMS share a tag. I could be doing something catastorphic.
> add sms share to article social share templates

- hugo/layouts/partials/head.html
Adds description meta tag to the website to improve overall SEO strength.
Using Chrome Dev Tools.
N/A
N/A
> add description meta tag to header for better SEO

- hugo/layouts/partials/article_modules/article_meta.html
- hugo/layouts/partials/head.html
- hugo/layouts/partials/homepage_modules/homepage_meta.html
Update meta tags on the article page. Adds author meta info and updates description meta to reflect article description.
Tested chrome devtools to inspect meta tags.
#91 
N/A
> update meta tags on article pages

- hugo/lib/createArticle.js
Adds canonical link to build process in ``` createArticle.js ``` 
Test by adding canonical link to an old article and then using chrome dev tools to inspect the HTML elements to confirm the value of the canonical link tag.
#93 
N/A
> add canonical links to build scripts

- hugo/layouts/partials/article_modules/article_meta.html
- hugo/layouts/partials/includes.html
- hugo/lib/getArticles.js
> Merge for production from master @ 3061af4

- hugo/layouts/partials/homepage_modules/latest_articles.html
- hugo/layouts/partials/homepage_modules/latest_articles_second_section.html
Fixes homepage layout to include all latest articles.
Tested locally on chrom.
Checked the homepage against post page.
```
'/'
'/post/'
```
I don't mind all the conditionals right now but I think we should come up with a way of selecting the top three articles. Maybe using some of the SEO stuff @Haley spoke about during her presentation.
> fix article layout to include all latest articles

- src/less/blog-v2/articles.less
- src/less/blog-v2/variables/fonts.less
Fix bug causing large ordered list numbers being cut off on safari mobile views.
Reviewed using Chrome dev tools and Safari responsive development views.
#80 
n/a
> Reduce font size of ol / ul tags on article pages

- hugo/layouts/_default/single.html
- src/less/blog-v2/articles.less
Adds parallax effect to desktop view on article pages. 
Tested using both chrome and safari dev tools/responsive views and using Ngrok.
#9 
Only on Desktop right now.
> add parallax effect to article headers on desktop view

- .gitignore
- hugo/lib/getUrl.js
Adds robot text file to staging and deploy previews.
Tested locally. with different base urls 
#108 
Using a hard coded http://advice.shinetext.com to build robot text files seems ok but it also means any update to the base url on production will create some serious seo issues. I could use the staging branch url but this leaves out all deploy previews.
> add robot.txt staging/deploy previews

- hugo/static/_redirects
Redirect users to new article with updated content & slug(url)
> Add redirect for updated slug

- hugo/static/_redirects
FIx redirect format.  Added missing backslash `/`.
> Add backslash to redirects

- hugo/layouts/partials/footer.html
- hugo/static/scripts/typeform.js
- src/less/blog-v2/includes/latest-articles.less
Adds script for typeform polls
> Merge script for typeform polls

- hugo/static/_redirects
Add redirect users from `/articles/how-a-distraction-expert-stays-focused/  >>  /articles/heres-how-a-focus-expert-stays-in-the-zone/  `
NA
> Add article redirect

- hugo/static/_redirects
Adds redirect from L%27Oreal-Thompson-Payton to loreal-thompson-payton.
> Add redirect for author with special character in name

- hugo/static/_redirects
Redirect from link `/articles/how-working-too-hard-actually-hurts-your-hustle/` to `/articles/why-working-too-hard-actually-hurts-your-hustle/`
> Add new article redirect.

- hugo/static/_redirects
Merge new redirect into releases
`https://advice-staging.shinetext.com//articles/how-working-too-hard-actually-hurts-your-hustle/`
> Merge commit  0b0985e into releases

- hugo/static/_redirects
- src/less/blog-v2/includes/latest-articles.less
Decrease width of category span(labels) on featured article link previews.
> Merge  commit 220bbed into releases

- src/js/components/Header.js
Add get app link to navigation
Using netlify deploy preview
https://trello.com/c/pnYXzqOE/287-add-get-the-app-to-the-nav-on-adviceshinetextcom
> Add get the app link to navigation

- src/js/components/Header.js
Forgot to add mobile view with commit 8331b2.
> Add nav to mobile view

- config/hugo.config.base.toml
- hugo/layouts/partials/extra/gtm_optimize_container.html
- hugo/layouts/partials/extra/gtm_optimize_ph.html
- hugo/layouts/partials/includes.html
- src/js/components/Header.js
Merge to releases from master @496b110
tested
> Merge google optimize install into releases

- hugo/static/_redirects
Merge redirects into production
> Add redirect for aritcle

- README.md
- hugo/layouts/partials/footer.html
- src/js/components/Header.js
- src/less/blog-v2/includes/navbar.less
- Adds gifting link to the nav
- Adds "app" and "careers" links to the footer
Tested on localhost with main homepage and an article view, and on both desktop and mobile views.
- https://trello.com/c/f4lxlGp2/128-little-banner-at-the-top-of-shinetextcom-adviceshinetextcom-promoting-gifting
- https://trello.com/c/rAXiVqSl/124-add-the-careers-link-to-the-adviceshinetext-footer
> Adds additional items to header nav and footer

- config/hugo.config.base.toml
- hugo/layouts/partials/homepage_modules/homepage_meta.html
- src/js/components/Header.js
Behold:
Local testing. Checked the header nav on the homepage, category page and an article page
> ✨ New Shine logo ✨

- hugo/layouts/index_default.html
- hugo/layouts/partials/article_modules/article_post_article.html
- hugo/layouts/partials/article_modules/article_pre_article.html
- hugo/layouts/partials/extra/join_bar.html
- hugo/layouts/partials/extra/read_more.html
- hugo/layouts/partials/footer.html
- src/js/components/Header.js
- src/js/components/SmsShare.js
- src/less/blog-v2/includes/footer.less
Update footer links to match other domains
Update join bars on blog and article pages to link to quiz
Remove outdated GA events that weren't tracking
Need help with setting up local environment!
Old GA click events were removed from the code and re-added via GTM instead (tested and launched on GTM already
> Minor content updates

- hugo/layouts/partials/footer.html
- src/js/components/Header.js
- Removed 'Invite Friends' and replaced with 'Send a Gift' in Footer
- Added Quiz link to top nav
- Update UTMs
- Link logo to blog landing page
> Link updates

- hugo/layouts/partials/homepage_modules/homepage_meta.html
- Update og image to match general shinetext.com (previously just a shine logo)
- Added pinterest verification tag
Locally
> Meta tag updates

- hugo/layouts/_default/single.html
- hugo/layouts/partials/extra/join_bar.html
- hugo/layouts/partials/extra/join_bar_article.html
- hugo/layouts/partials/footer.html
- src/less/blog-v2/articles.less
- src/less/blog-v2/includes/popular-articles.less
- src/less/blog-v2/main.less
- Update blog landing CTAs to point to app store
- Add new article CTA to go to Squad Promo LP(matches daily.shinetext.com)
- Add shop link to footer
locally
> Join Bar CTA Updates + Shop Link

- src/less/blog-v2/includes/popular-articles.less
Restored mix-in that I thought wasn't being used. 
Locally
> Restore padding on blog landing page

- hugo/layouts/partials/footer.html
- src/less/blog-v2/includes/footer.less
Add Pinterest icon to footer
Locally
> Add Pinterest icon to footer

- hugo/layouts/partials/extra/join_bar.html
Change Blog Landing CTA from Download App to Quiz LP
> Revert Blog Landing CTA to Quiz LP

- hugo/layouts/partials/article_modules/article_post_article.html
- src/less/blog-v2/articles.less
Add affiliate disclosure line above social icons on blog posts
Locally
> Add post-article affiliate disclosure

- hugo/layouts/_default/baseof.html
- hugo/layouts/partials/article_modules/article_post_article.html
- hugo/layouts/partials/article_modules/article_pre_article.html
- hugo/layouts/partials/extra/pinterest_save.html
- hugo/layouts/partials/footer.html
- hugo/layouts/partials/social/author_social.html
- src/less/blog-v2/articles.less
- src/less/blog-v2/variables/colors.less
- Update FAQ Link to Zendesk Link
- Added Pinterest Save button on image hover
- Disabled for mobile devices
- Updated current Pinterest icon with recommended attributes 
- Updated misspelling of Pinterest class names
Documentation: https://developers.pinterest.com/docs/widgets/save/?
> Pinterest Save Button on Img Hover 

- hugo/layouts/partials/head.html
Adds structured data to article pages to support Google Search rich results, should we rank high enough for them.
While it doesn't seem like the feature itself would help improve our search rankings, for any pages we have that do rank well, it can increase the chance for being displayed as a rich or carousel result. And that in turn could boost organic traffic.
https://developers.google.com/search/docs/data-types/article#non-amp-sd
> if you include structured data on the page it can help Google better understand your page content and increase the likelihood of a rich or carousel result.
**Note on images:** The 3 images we're providing match the aspect ratios they recommend in the documentation above too: 1x1, 4x3, 16x9.
Locally tested. Here's a snippet of the data added to one of the …
> Adds structured data to article pages

- hugo/layouts/_default/single.html
- src/less/blog-v2/articles.less
We've already been setting and getting the publish from the CMS. This just now renders it to the page.
Locally tested the article page to see the result in the screenshot above.
Messenger has a date requirement on content that it'll grant broadcast permissions to.
> Adds publish date to the top of the article

- README.md
Update readme img link with master => main branch rename
> Update readme img link with master to main rename

- config/hugo.config.base.toml
- hugo/layouts/partials/homepage_modules/homepage_meta.html
Update meta tags `og:image` & `og:description`
Review using deploy preview.
Works! 
https://shinetext.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=SHI&modal=detail&selectedIssue=SHI-2216
> Update meta image & description tags

- hugo/layouts/partials/extra/join_bar.html
- hugo/layouts/partials/extra/join_bar_article.html
- hugo/layouts/partials/footer.html
- src/less/blog-v2/main.less
- Update Blog CTA to point to Web Homepage instead of Quiz
- Update Facebook Page link
Locally
> Update Blog CTA

- hugo/layouts/partials/article_modules/article_post_article.html
- hugo/layouts/partials/article_modules/article_pre_article.html
- hugo/layouts/partials/extra/meta_twitter.html
- hugo/layouts/partials/footer.html
- src/less/blog-v2/includes/footer.less
Update all social links to @theshineapp 
Locally
> Update social links

- hugo/layouts/partials/footer.html
Update cta bg image with bg color
> Merge to releases from main

- hugo/static/articles/test.html
Create empty html file with GTM code
> Appsflyer Smart Banner troubleshooting

- hugo/lib/getUrl.js
Pass required err callback to fs writeFile causing netlify build failure with the build image upgrade.
Also prettier formatting.
Tested that Preview Deploy build passes. Build is failing in staging. 
https://www.notion.so/shinetext/Sept-19-deadline-Netlify-build-image-migration-29e199347ad24469b6f1cdbeed0bb07d
> Pass required err callback to fs writeFile causing netlify build failure

- hugo/layouts/partials/extra/join_bar_article.html
- hugo/layouts/partials/footer.html
Update join bar cta on article page footer to appsflyer link
Remove squad link from footer
https://www.notion.so/shinetext/Update-blog-footer-e482cf33a2bc46d9923ec4a3a10ae42c
> Join bar updates

- hugo/layouts/partials/footer.html
- src/js/components/Header.js
- src/less/blog-v2/includes/footer.less
- src/less/blog-v2/main.less
Remove deadlinks and add /podcasts link
Remove white bar between article cta and footer
Going to review on staging link
> Remove dead links and add podcast link
